### ISSUE TITLE
peer with bad top block below checkpoint 

### ISSUE THREAD

**Issue by iamsmooth** [monero-project/monero#122]
2014-Sep-06 16:34:25.234589 [P2P1]Remote top block height: 202659, id: <78fbbca5edea204b3ff5e92fbe6413029a32849ccad434481cc9e2b944244845>

This peer is definitely below a checkpoint and probably has a block that is not on the main chain, so it is of no use to us, and in fact enough of those peers would fill our peer slots and stall the node. On the other hand, dropping it may prevent that peer from syncing, assuming it is not malicious or bugged (the latter appears to be the case after the 612 attack).

What should we do with it, if anything? Maybe drop if more than 1/2 of allowed max peers in that state or something.

**Comment by dEBRUYNE-1** [comment]
+question

**Comment by Cactii1** [comment]
This looks like it has been fixed and this issue should be closed.

**Comment by selsta** [comment]
The code has changed a lot since 2014, peers cycle now too so I don't think this is still an issue.
