### ISSUE TITLE
MGs json broken in ringct

### ISSUE THREAD

**Issue by moneroexamples** [monero-project/monero#1448]
```json
    "MGs": [ {
        "ss": [ [ "fb90b21624c8cadaad85a517b0d5bee92f4cc3e2c44ed464e6bf7770f830e502", "e992b731280092c207fcbe8d168565af0671c9e2be802dada5c6af1ca4e6490b"], [ "9dcfb0e033230069bdc88e4b5b9c9a7779efd929eaccb1b7290107054be39c05", "1b4ec23eeb606145d8e031554fd056a2d3e4ebe5aa69fbac379c2a099da6640b"], [ "f7f98c9f91f0e55404b689e0826e33d4d4bfa33d3464cc4946c07f8283ac9502", "1f9efe9d19fa44ddb442db8dfee4fe07cb71d3081d15719d86eeab7175f61b0a"], [ "708088d68772859e71830fef14976fe72be40df4c696466931a5635690c8160c", "ffa70c367fd282a96b72d4370abc1c3f48a59142b618dffd1dbad7d208332200"], [ "8b5e11baa7672a22ca0db3245b4fda79d3711e036428669fdbc5edbbb37a3807", "9ab07d970d2817e10053327f389971b36ab14bcafb66d28191d1bc1cf9111604"]], 
        "cc": "72372efb964ab4c0cae0800953e34ea9f46f70f1c50d7710e4d8d9bcbe80190b", 
      }{
        "ss": [ [ "ff6dc943d53d3a74d05bdc0c46f1f04231b70594e89365b72e442dc017e3f00e", "a63fcdf5a61eee003ae5c392cf97c6d28c368772d6c423e4d7f21ebbe2123604"], [ "e91f04c23ba9aa1c8f4c434e59c23f3456e1da676c06ace70a9fa463e35b5700", "b3e3442ab3e46e38e88dfb9c28f82a812432b82c7c2ad9b2547aa00516093d0e"], [ "f37e3506c0042bc3cc7cfae604b77c2badee0ad50eb8bde74bb4b80ef3cddd03", "4bb9c5261cfe33a5ea0abcfad95f22ff56502bcc90b7d6de32febe0165fe220d"], [ "7906c9eb3b6aaab6ee6d2cfb297065486d101b684a14c0adaaf093714176bc0d", "6235cc89181f82ded88f2ea4d00ff452de7082866c1001374c2e5820b76f9309"], [ "ffae141920f6443e6175b2f112e355a4803b6217579562341c07b0b18dc9610d", "051aeea8aa5fa6367df7120051fd71c95197e582966624618f511608625d5e0e"]], 
        "cc": "1d54733bdd58ffe8d6f415f035622b9b95e0c3dbd99d6401bc361aa15c9b8e07"
      }]
```

Notice missing comma in `}{`. This breaks json parsers.

**Comment by luigi1111** [comment]
Fixed in #1449

**Comment by AmritKumar** [comment]
Seems the issue is still not completely fixed. JSON parser (available at http://www.jsoneditoronline.org/) fails to parse the following transaction. It seems only the RingCT transactions are poorly formated.

{
  "version": 2, 
  "unlock_time": 0, 
  "vin": [ {
      "key": {
        "amount": 900000000, 
        "key_offsets": [ 50295, 21561, 5760
        ], 
        "k_image": "a59709afed931201b7f612760cbd36b117a497808a559ae8ac21fff8cce88e17"
      }
    }, {
      "key": {
        "amount": 50000000000, 
        "key_offsets": [ 232488, 17928, 29278
        ], 
        "k_image": "746753bc3880c9b7e16e8442d6943d6ee1ab7895195f0a1e6145699cb099758f"
      }
    }
  ], 
  "vout": [ {
      "amount": 0, 
      "target": {
        "key": "1a6d1a4bf92725432ae4902db5dc244a4dc5910a5cfa93a938e12727b59efdc2"
      }
    }, {
      "amount": 0, 
      "target": {
        "key": "aa4f6b08774cb707053774468f4b4bd143ae7fe4382fdee5590bbf4caeb4059a"
      }
    }
  ], 
  "extra": [ 1, 150, 177, 158, 178, 85, 71, 17, 91, 104, 228, 179, 233, 249, 152, 91, 170, 16, 253, 208, 136, 126, 44, 30, 158, 21, 240, 6, 159, 162, 101, 45, 255
  ], 
  "rct_signatures": {
    "type": 2, 
    "txnFee": 26000000000, 
    "pseudoOuts": [ "fccc08e420a46354e874b9e6ff299c1d25d6c106d762bef91bacac98a9d043e4", "c273f46d6c564b68bd8795440193c11559e87502ab5fec15ecb2ad62151d60df"], 
    "ecdhInfo": [ {
        "mask": "d1130d5eb0209af30b9fe9ad93cee3518cb7e7220df5546a9f531c41de235a0f", 
        "amount": "7271b68786eb695772ad0a7b8bfc797bcbf53e4fc5e2972f452e5224324af808"
      }, {
        "mask": "232c63be4f759e3cd75966716ee58069a6e3decec75d16e6ca8b4c6dc1deb803", 
        "amount": "089214e59e88109a8f1399c3af64f525b67087f45b960fcb328d09c689011603"
      }], 
    "outPk": [ "cb327a63e8c700a5f7bf89fbff9e2a7d20b771d6d0494bd26f7675751fe139df", "c3a84eae22b7a154fb8f56da5a614026201db6cb6a062fc7f47d0895099a2064"]
  }, 
  "rctsig_prunable": {
    "rangeSigs": [ {
        "asig": "4eea96a5dab6e3a480b391adf04c39e8ee37ccbcefa1b124f56994fb7970d201031e7c13ca027161aa45571e164ff764667d7c9a26e9e22cfa0c9341ac9690053fcdab5bd7473e18d87545e99c407843d3d95ed6eeae6a2620f32aaac831700cdcb30f3b0d3dc484e39700cf033f71a69d6e76b9268f2a9bb21015510085d50076291360ae340434c4eb9cd39a1b68f427bb4b2b1f78996d06f8820862965103d556ccff7efaf6e851d2197a6a58e6bbf42170dd594962626fc1b4c958b0b200488de931c406ec69625187f175d46b776f28cd4882f06ee07b049aab6a9ad40ed672b4851ce8c6fdb997f3d9750dd4876c95e12e7895c322bad0505702943f09c70d9cba85024b2e481afea7cc1851c72e4f0120ca3532d163c81657da3400007d1e1f5753156ad01899444a3a3290ad9a48c76595a1ef2dcbb8848908631503394d108f477d3e05150469c91c568e6e88cb8b92c5ae0c50243859bc3bcdd207bed487a963929bb483bf1c61d0695ee40a9cb3b5a22e2f2136577aa4294416048823a5c1c6cd7576f26cf74efe931d6272ea6565044ddfb3ffc7c6576bfd270f4225a7eb0efb03abb61333cbfceefef2b8d229104b2bdfaddee9e807dcef290e868bfca5813b21b4615a0b26fdf7e958edd61633052df443fbb9353910320e075717ada6983e225b072ff80e57383e5c683430519339a5f9f3bdb0698735de04af52d090acec9451d9881ec32b853bb5806cc56f44d20feaa56f5c71d6b9c6069b1390ae85578f33c96061de0555063e79e7dda7673babc01c97d90674c6b009afd4fb45e488036aa85731743cac3a8e8d0e75172abbeed331dee14caf7c440cd68145b4987813bcb58995e3cfa9502885cea9dcd89023f0050015aa06f83f0899cb47a811c6d3ecb1b223bcf47abf5675830ec4c8afbfacf799fc917274ce0cf190256a5367c11f62c7c4cdb1ab167fb8d2b0b3b722c95a25b4ffaa2125b406c14af35e9aaad6e23702bec50c6a3599828744168afe441e58043f461f6601065c49da3cd81c023ed8f3a1717eaa92160db473d3ea244e2c3bd6913caec83b004123b08adc5ef25097197826e1e1872578d99e667194359c0f4be3b1c0811a060f404274f2e07f8395f624ca2d8038233df0c38289263d24701530c258ca290ee7b8cdf4ececc011df4773c30d4b663fc16d41f5f11eb23be175d0469fd21b05ba7220aa4909d1e93829522271f2568eb4ad8f953c31806ab776505c51b5ce0889421272b21a8094e141d16fca38fe49abac33b75eafca4a9ee377b18e5be40aae959a5eaa1507e4423b9313dd065ed74bb33a27276db16ac97e8355327d2106405f8ac55a533a330c9c1cb4296d3f4cd0000f1cea673b9f020bd8820c393c0eef729e7854362d6514dbf72aacb430fb3ee9914e0a20b30b9734216875ff890ba2362aca7891c423b3fa3b7e01f0acb42952bbd1258134ef30b16b2b0fa61209743f9c8aa56e69d9e45a58207b219f728d154375be23b15dbaf634b36740230f2ee627bf61a9f20ae2e7e5416b39862f83070513dc29c88463cd4ac627a228047e4d8f97fb8e1cd5c2154f8df4d7153cd5b179f262defbe42dcfb40cc714ed09fe9b5c2a23265aab5273c40c1856d22d509818b4accec65fe2b2538d83b8fe09f4678748e085cbfd5f8562ad19d86ee2f728279b4fc8708ef3239af777787107d33b42af47c4f4b01d0a5f5475ac04d8be672c64fd0ee374f4c9b3e5c2be4a0660699a3c7f78e3c7ab669947ceed1bdd730462361d2cb8f6e1461b574686510bc06810ff5518934029dbd7a9f1c0f4071d6c181761c20d570c30ed3b26ef050c128d361c35a46cd703fce1d0e5cf44ede8526043961fde844454cb9ba06973045daa7a8d4a5ad6fae161e2f323c297220c1256fcc696f59837910cb4e3615d02ebbb5f426d2e1d6f348da25b3a626af5bc6d39389d0c833dbb55541fa16bbd0032b74c9ab3b5607fca7e1a9c01b3adb1aa43fef6aeb43dd53b9eaf049ae3ee02b32e1b96760a2c5ffcc84705e2faf869db0d12f1465656e45ad15c48e10a0603c2023a5ce1325364082c8a2425bf6e400a4790942646c90cd4684838e2642a0df51b917423e1d513a65c5d9f16a9d99f9257831ac8d2cf32ce3c3a44f6ed590938a146cd1cbc52e1c9214596721f5425bca7b822d2ef6adbf50a0f44d7e05302efd6b5f145e469019f53d397628dc838a2e54cc4942bff84cf6375afcc673e0135de78e08fce5f560263c68e73013d7006f3886fd1970d1eaa8ca6095f94b7031e012597cbcc624ba655b36187b0f7550d92e12baffcae2363d8e7d89ae6bc016caf76bbfdbbc97b30d3729d6d1644095a99795e6b06bfa3011f80a773a77f0cbd616ae0f2d0d8aa5186c00fb37ed62ba16c2cedc5ae4738384dd9f134ec33089ac880236143182786f0a7f643908fcee4f69dffed9843641dc7b9aae8cc8004918821bd615fe11df1b41ad54d3a2d07f657d1203f219ebdae33973a4e20280e50f90bcead7e7cdd7cdd3a543ef9ff2485dd84fb73726e7b86f0f8da4968bc07f57a558bdc9ebda58fa0853f4b63122e2ac40004521d2109a5760a8df5e3f107d3b20bf935862ca41b9c72e0c4a2dce610cafe1fbef04110cac1218ddfdda0059ac08b4d2937e5626c9f769aa721b80b9ba90cd04e92cecf50bca50a8de76c0852a2544019f3648dfc9c4849712127099fc3fb7f0f1316aeb56787f3113d16099e2c60f63b388005ccc526f613b72fe317153e4bdca7496ee86f04ae7d223906ae2d39d0e41584441c0d8bca4d5784457f452a19890537392b0eceb2475d3c0df21663c047525893161d3c6d5a4cd696f7059baac6ff893bca4c87481ab71d0e5e65576ae805d64d6e7d86c3d33543d18779cf9d55f8c599556abe1d61c7e3012200f47b1b6166d8a13b7eeff138915de3006984c4a69df7caaa7aff7cce490c537aeeac725c000b0e639be91308d40ffb7831b16cb68a6325c713d30d266301152eef952988845863858a48c94838ea174c2b4be9c27c3fe4869b885c10010c6cb3a0c0153e3053f9f8cc36ed9fc136e1dc4b0ceeb57a61692e7f1896568701fb70541a38cace20d0891ef12c6b14fbcc27a08eb48f27ef93a1f2d1785cb60bccdbb44480eafb57eae6838c1d0e5bcdee32078abc0d882835a8902360c1cf02573960362906eca3172676bbb815e2dca44912b5120c01f14c9e42c5af45340f8f05ad26cac6ffeffd220234eec5df89e60b38c9b5298b84d08f485b49ec8e0c2a05c05e2350cd8f497acd429106de23a36d93e4ae8de54a483d53b713604d01dcf2346cdf72b29cdc43abf44dab49f7306805ab5418b2684c4f46d65900290900c81bb1752e3c4370ce8e09d517198c7663bc13694a57129929603a03e2f90dce44cda9ab9334f08b06e1a235f86c523c9ab48cae2240578dbca9637dbaf40ea713b01b39218b128c0cdcd6354141200facf5f67d7d52859a0c53aa3673e20ab491150ee05105bfc524ff2a5e025cd769f14fbeea0ca7ef4313d95700894001aacc5d535e6f729eeb46deaa36c7945f686a3252fa23396fcef00d4dbd1e7703be3f2923d1bc23c14f3ae9e8fa71d9fe03df72dd08b0c6167ba9b8ec045fc8069dcfb5ac429ecf450d79d79c213be4cbb1744a72c8104e19e62db8440e42f2014d5d997d304bc8fcbbb6445b0a8c4e0a622bba5b83c0150d38e194a7bec9350eec6da5113fc59ad167bbbc34fc0cd1890a6f4fb978bde66f83c2d020f42cd801829f149da6d92bdacad22c29dc89ecbcb77ca1f6ddec8bb3414b9b0291700904e55609fb49f51d94b9955d9df76042d34c092e61e6ad4be24f0b1e18a3ce0e0c1cfa838b171184bad57249954bb021a28f6c217f30b4965b16ee66ca942be5029a2279c1340fb6d70f355178d42b9dc53cc3b9b9408a725aa375670d1c82bf0d379c47780d24ceaa2d0c17aa0a38d5534ec3544a0de9c0d8b76de90ec13bbc023ae8bc95ac9735cbb85331411b7c19856ee9b2da01092f2c894ca1dc080fd60bfe2a0015ba6f878287c8c22ac185f0f027ce30d321c8ecf15cc79f2b3d569f02d6595d40e56485e0b69346f56c8b3d6a427f6b528a16512410ddf6d6ac92a802f57ff993842b267b79b1346e2ba2abe7e90b954a95bcfea00998d4779eb8e205b0486f7facda8fb1e0fbc600b39ab4e77263bc2c65b4acd8dc0930ce6874fc0ea1ad6c57f025718a6924202f6396bd797826419eb86d63dc35f53d2181a3410896f5d670f7c7b445f8a45e973702505d201014121dca2ef1cf3b7c3a3c87d10054af1466174dcb6b0ef69436683696f35ce81dc7f79a1885a4e5b784e7ad0e0a7071f2263e72d638a06b49e1e2505920c22a7ea02a0e2991fa49663e843a980307b64fd80ae34a0208b7834cdf0a50150443da385b3bebb14fa27b5ba8a08f045a7f43b46611195c4f40af7c98611ae3996066cc1969709c41340ae112b8e3030bb27355002ee512473d67641fb8cf03abad0997290a08163d88b12a6523b206aeb226fac2fa4cf1a143bf3c8b44b546d279f9ec619017039594da2a1da7eb04fc06e8faaa5f4a3897537c6e1fcf4f3b026e424950594153283b95f26348aa0c96f68e45e272f71e034056cca1c7dbb85c5ded3ae30bae57522142980194c100a1e0ba958ad6eb352dbac89e0f072643b8076869edc451b92faeaeccad0d16078534d7b03d8175b9dd554a654594e5e36d42d46469c1ac76aeaec5821db9ab0f8ccdf9a432efbcd4b706c7c1af8000589afdedb507438778faaa641112797e000608e47a38bd665a8e900981db11569133ee60aff31c04344a74bb698dcad40777fe05bde6ac7a42cf7ce770d1c84c7a9af84137cdd44cb9a1f9590ecea4c0072610e4e394f428c90c78aece7612f388810d834ad91351bff19d5d8bed51110f39a77f6c57f06e9de02766af2c90b80a9684da51275c770cc8a66b4851070706886405a2f06ac8fa7cbcd703b10cefe40f8dd6578d553a8bad4c18ac6bb4c707a65cea07d59ec8e9dbcd6900a5f6c30094a11b71b3b0bdaadaef7a7b89a7e80df56c9374c2843754c5209a4af7fcafae3201f5f315c05b06a14b0bcec9b4240e83950d99e5813adf59755d6ce2a0ff3ed726f8cf879f17af1fa5b6eabf3b7d02e53e290cffdb9b9e95ca2736a5ef19fe371faab5cb53a3a7bc1ad7cbe195cf04ffe240320fe6180b58aee54074739ddd92924e52389ffad2dd0b1097d02be500ce86608abb778b5f554cc0a180ad54703aaeb059ea2bf872db8256838e194a08037317d43197168e7a7581cd8269a3b4a60b0c365d52e46e0ee4977a652177023441985bead7b82455e11e7db8feb6a6220c5c5a1ba1d2cee813f895ae48f906bb47e4fbe29569f16d63beb80b7197bd1f29e650dde9f63895f92db98a401c0d4e2f2202bb8aa4d2c922bc8c4089525b4accdfbdb0ee561f8d6542ea751b3908be4aa097a1cbb074f0b1f389c9b2ae98a59946f83128ecdd4ca93ffd3f9c6600f11e4c600a03316edb3afec015413f02d360c471e53f43b6c4b84ed6e2c9ea083752a8c89b8651c56f8200c200c28efee4cf3608045e81cc2d0bce3c9ef4ce0cb8c3181399b6d463bf7fdaf967820f4c80f3f76439a1517226b2cc0e86a04d00f21335c955dea1a437f7cf572ccc85b915c6065e49b7d16a050468278163d3089c9a201465409a80c7772e82d82f85d986824c8fee218cae933169a79fb28503b4ca7add194b47a60977e02467318d7304ac2eac94f0c610eb3de587cd611102", 
        "Ci": "cead4ccde5f7ba1b3864d18687c12ed4d04ae42ab811555479abd6f01723ce3496bf0622fc22990de389a9fca9354c7879fb3df253d16a9fd8078eb5ba0f4a71af6306458df8b2812430e40973f17ff47cfa39732beaeb6bdebd3b0700edf92a2f2f4d98870667e2a0633de156ff40f27f69e0d45addbf3eafac90f7455308401ac50233f1c14982cbae58229cb9cba7bf119d860afd577b35218300dfe0d9c40f29b5753ce5c75e2d2a4a1cbeae796a5dcb632815f188e1ed0bba57114e7fea8beff22aa836b7d6932c83a62a7271d46ecc4053f1735bed9007cde368aa65406fcc6462dc11a4fb14b0caf5ee5026a992fce22c1f656b711f075816d3e09ae399806311a6f8680ea006134abe3ee13f0d1796f9b051cf3aa7b6206177174d81b1256b061fc726a1d89cf93eb40aff15b7aa2922c15f03605e802ddf3dcaec58171482c462a595bdeaf9dcb6eca34882a78ff0d924972279e94439d2d0b718a06cf955b8dc4673b6abfc0c1f416100c0fef9ee290614929b4442286ac433ab1da9de7b27be85d87b2d9302958da9ca5a7c350b58936271bee5a68b3cb9994ee7eb52fe4de54ae5537f61c3322d984b0447155ce4f4a7e2ff986d54d5b6443a76c0d8bb8a8807e63b3b3c0d2f0f9ee0083b604be826e9e9d350d8aac7a14d6cfc275a82d1e4e5146010d377787d4d6d1c7ace597bac8ecc12321521a1241f6a64901c195dbd4898dcabd68f354b663f1cc09e9745da7696389a3c0c681513bca8b608b2c13f3bbc33ac2883606b89b401ec3c8a88e448338bb67c6f3ef1b8e35455a575b355cdfd2ba48042fe370e14daa402e93bb320ceefb15a4af287e6b73a90f351cd66ca52b639e09574dee411524e471c5e7767e4b73e88c2615f535ccbb75dffe4a9faffd2e861710283aab9d4ee18dcfb56f964f350cafb60cbc491fd72da3bdbd895ff041f979ed7013db785ba8dfb47e6da76d022ce95c26e273c31bf2ea4e9d649e39ad680d1fb3a004fedfe54b8bdbf6cf026f52931623a90bc0ec8ffc5a728c189775f3cd69eaa01ef32d5a4d92da1a759ec17485fb9bd60330e03355cd0faf7f383f6a165bae6f96ce5004e3aa4115583218222af13807a4a6bf98eb4741434865b9e090431d2313026b5e568f3711eef79acf4ff12d59469ec9118ec76e2344344296c464d0306038bc1335ad1ed475fcbbaaf34410038498a0af67a501c865e552186e107668b1d95cc7497921f147e33d76563ab516d194acb7c9d8e5aaf5b8bb78f1a1d288a5dcd15cbd58ed655baa3b6a4b685096771571e91d8819625faa4580c4b9a0d75c0384714b72c538584573bc1d4490d1e513ee27777dff6630868f95873a6aa38606820792e3cda8640e90aa9be86f190f0ccf1e1f8842a25693a7ac3e6049634fe3d6cf5c0d3f022169d82e99488b4a4fa3e06cd14014aa9f33ae5032950bb591078d1924ecd43f038b07a49560da22f552bafab9c81458055f7dd181ee900243322568d1a8f25b21bc9e89a29cb8694f569e9b0abc46489d415074d1eb8c6d28c898514256cbc5c0515523a4c08ca73570f5077a5bc783af939225687acb12479a87b8fbe27b7be23befeb614ea81883feac477d02528a737a07acaaf06fb82b197f9367a2e4ae8c1862ad2bf445affba3c1b48cf348480b8cc7885a71a425d306dd8a43aeadca7a5238065012248afc02178a39416cb6f2221c7ddc2fd2d83be3239ff485ef1473ab9efe7d3418d47bcacc4929dfbe9c4d73024720ce4c8ffaf0f4237cbb4767a7d56bb484c076ed9a4154513c8ef4e17375d4003579a65d7782ddb5c968751e866a790b71cd731dce069812485ca3ddd6cef56c45e2e2a7f52f35d3416a61a444b3641dfb26e96e2e50ebedb0aa2bcfd9b461ad3cd4eca7c20b0c216aa98a6f7d0bb02ffb5e3f5e07b9184fcdb1834aba2f75185e5fd1f7d8ff84b47b1afca1c8297fe6df1ac2b73a3df43a57bd477a615013d7f1502407b1505565cd1d0759af78d81a575be91eefe7280894a27124896f267af4371f5ab48d53246ae4dece69436cefddf4e1359441782603ee4485aa6b3d70f6d0a2883eec5a3d26023e66b85b4fb9d1e082de1f0ea22c06628a3eb3c9b7663306e2982d7af60059dd8e416815eae0c842cc643a05ab86fdb7d33a32509b4b565c2b13803251a1e89ae908940dcf775bd799bdaa053a9af8ca0a52380ea5b2c2199125cbc7ab2264b0acbf184ebd0d51273ca05df1e3058e4e328742023d54aee70d1e8f2ed2ee8684971ec782e738c442e1ee853f1a3152f2f6723c94ffb9288108cd42eb5a67cc5b25986bac28b38c48bc0df45c7345b4ac2d94235c8b11fafe4de7539fbb3d2951187c9026ffbb4ddf86008c12d537ecfa2d0bcc6254eda7733f755fbe7f3fe4d6c40c2313c04883f24d11cdafcae213d80bed04ed37d01741424e87994c9d65154105214c922fbcb99e5d845611a5ec88cc797437d234af39ebd24122fb5d21627c98d2436df764273ecbea4ae21184988dcdce8d329cd898aab387f8cdb6a3b51a40a7d7877d4809345e55b96e20a3e8a96626cd9dd5b6bacbbe8308c1263520add2898d5ba40788a2859434ce3fe503741db617beb2a39f83c3716132f8b608d3c3c2f73da843b749801dfdf3c37b25a0d547c4ff94b4b5e5c737a477d54daf5bf2ca02e8ddbf666d417088af6d9f8bee78019d849910c845bf1edfb9a6d09ad8d62effcc69e57aa41e7547ad37d03186b213fa001c38c3471972e5826b5f50130860faeeeca0cd88ae5d7edce3418b5a8d2f6493242a87fd3a19be53978ab6295ebd4c1c03ada5e7266feb451d950fccd7cea756dea13b86f37caed186a5c7e35bcbb855ef7bee7c7368277"
      }, {
        "asig": "937b12377c1566e71ad8f83ef1ca9bcc41f59623918c6579854b33c3ecf7bd04182687e7fbc21a678c4fc29876d0db8b40146a9300cbb1581dadcb279af24a00e2e4171feed037c7199c06d26095adbfc1b3befee68b41cdfbe124e511db3009904e80e91f490c582f62dbe524a530c8d3d5e017d99dae09147fdbdc0ec2f9072f5a20c046b11194329241841d9a2e19d69f01f652b79abc43114ac3d99a8100f30cf5e14f3ebd253b9e83ce04036f648226d5403efb8d09db8171248bbd940839bfb0dc2d569e87c3bd8111dc798f0a37f235495d71aad07c1c3ba7bbe46101410ada7bc9fb5247b89f56e02163c68ef85a4cfc2cbc35131889c07577558d069d4aeaae030cb7182a16ff35e527f1fa6cd0ad02b63501a1b80b97992d02f003a43ea99809d4b59897ee24aa5fc06feeafe8dab1963663db5df4b314ed12830a1cf4a5eea329688a474724b7b598586701d08cdf21d92f91bb594c428a0a380ae7d361d5b9df40d9c8494fefd90c2ff196cb7d534d040e97e9c6d3676c0aea082eed6264aced68d5dbf3ae1e3b3e6fa409271aae800f73ff65da35a490f0e2086e7b36a41c84be81e60b8ccca41a85890401625031d2e55aa017c3a3c1b6ff0f13a4e45f2e5d46157695632bf23bd4a1e8584e5c5dfcd826330bb445ecad5b06be5e7f77a5a248740c0fab5fc5313ead28ff4a58246a63051371b79dd632d709587c4955981a770f334fcd9249736e1d405d22c21215f1f1d14acdc44581630557a0dffe09829f2e1a1ec299e422a1c129960df5cd7f4ca2d3167f85eb7f63059ad814b1cce8912a63f887c7cdeae5a93ab93e4c0f605565bee0f6b1039af40e8a6bf5ef31adb388abf4fe34c8123fe5b2131ea0a90dc0987b57069e9c622a00e2198bcac317ac797a4836474a11f3720b1d78571571567b2b6a26b9361a450c05d6b48de81dc8b2d0d746ef3a16008026d6159d964817561b030c03979cdd0c33d7180b49f9efc6f93a9f7ea5c1e81b42735b0b2cf7f0ec18a16316532ac102581dce2233ddf5eb29252748cb8c470bade732c0d3addb9003eb94ae565b0504cc884e0d353593abe7e6b4148ebba7db190fed7a0045246d5e81899114cbab011ecd6889ed3286e9ff6d569975599ccbe80223ea90f197736b601dd7faa4f901111a06365c444fe3456838f2b4b558663b63dead6e2632562d1572c361d9d807e8494ed602b9ce00551d398caf58eeb705afce044bc9aa2e879de0a853bf6f0cb9fe2bafe4d90fe064afc792e281b6b6e82e30f39e8abf1945770594ce016f020db12ef27646ff6f966cc8db17ee71c5c60e62678f648783e5731072d786ee0d955287ac1fa87ecbd11fa523b57b09e37c47cbf849eab91e9cf6e4c8293a6f035571b6ed6e84188f72adbc8c0112270ce71d065e8553fb3eb41973392eb7360fdef0a55dd00c4755c259f54619c089035d4362599d55a02591d0b0b090afce06eab43f15289529cd0b3348a5d54f79c7e94e312837193188781cfe231189c806350dcb74e788b380137a2bc4ceaa908de25c258c8649bf1c22c18b74b8bdce0ec1b6e9676bba61f25c47af3e5b8ebe96854c8e0b126c2ae23af02ff061753e0c9585400bdf868735bfa278c51e61f830b2eb691b3153fd9bdeba1564e09f470ee887a044e555f436102c1e2fd7c5d5869d06199531d6637eb020780629748104425ed041ddc6abd1447f325cb0f295dcbb3c6f772508880d570fc863e95fe905191fdf9cd99aa45f703da685f20dd73e5382efa0190ec5c58c2e091f240d0801b1ae54b04a9e1ff6b910ac8ccfc361e30fb18c0a8d8b503bb4ab98ebb956770c3f03a5a310ca206c225f512fd0bdd1396ed4856caa34d283b0201c64d2991607fcaa0b04937931ac63e2244f7db2ee9741c5b7c29d77f14486c5843683757b019c97da68517058827ae3719e800c4b9be68282fd6e4905b6dca5ea4034e27f093e0dac03649d8d108676dc1f0ca24506bb6ee2668a3ae6fec4c8b5c3b93b0f0981a9051a7727ed875ea30a0563afe6b83109cad782e9decee9d594dfad85160d029fbee93ea0d67cc544ce45c270ea6bd233c9e45a5d2d65873559211f75d502480e10896770391567c114d9437761fd2bc42437a71ac37efb769c5827e02d0076be1343d33d2618c211ae4b9798bd036ccc0bff2200e80246b6511bf320f80a73909a027101c073eb2c16748d87b9aa7cb2a41d2429779dccecf77ae3492907b8dcab8bfefa352bebfa9c9a98f1f1d203f818a3bcbd743d50c8e1710d28210cc2539344029d633c16134a0135adbf91fa6f2bb23e2cc70653cba5308789640d1d2941d7ac5339dc35eea17c835f590b5494225ab1d017bd111e3246253c8f073da8ead0e77b94ca47f793fcd43addc77459010184c02592e60eafb69f54280b64a543ae12acd71f4c97bb7052501061f4568e9026bbbf6322faad0cf555090bd50519513811bbe1c1651a550158a35d6ad9562c1bd2dcc0e1ea779ba2460a05854aad33662caf997ee4ea9a010335568fe9f02f34506b9d18fb34cd66a5f105d7378fc180720e4d4468beef43f941287baa5438e21caed7a9c6d1d7a275c200bf8e1475c195601dcf62fa33dc9d84f206f5344e68f2184cd92092cce3e86a0a7c027f03d7b4547ee93ca560b01cd6434c095a64be5dd1555ec1c0cf6ea2c20a653cbb8af08f75c088565c89ccafb0992cc26b4d52c0b66e883bf651ee556c0148bef40459babffafecdb8c4dbc8d10fcaa6b79211485086911153ba2e2ee70deb011a8f02e2f744d48e95c7e308d5d07ce3aebead5835392cd06b26958ca200b7166a7a9c8aed9b1eab90ccdcc39e64d19faf34bbd9b35a681ca4390f67df0fa95ac28901bf97a968847bd49fefd5ef07bc748efe00ca5d646e88de7ce3e90e180b268df9beb5a3b4b07e4a7520b7d2c699c028ec05437ca4602e8751ccee0e83d94b601517ea6bf4cff36fb3635e330be88b626bb7884abfe4a0ffeaa803052d3f252b90afac88c1dc21eb342f3c7a85a7df819c5ecaaa40c623305f800101ea076dd34e030e2799013556a73cb58c65cf93a203b250e8b08137f4c35f430c32634e3af4a6e1f85b75e380eb2daee56994834dda4bb498c0263db863dfd40502135f20c1f380ff8a708f2c2e1f2c5af92b109aed11477e95de359e75db4e0db54c82d65923408df40a96678dfeead5bb4fc4bdb3be53bec0b9391d9250680025c591713dd6300156d7fe20f1af78b99716c17d1764ac11b38a8d24804556009805f12661fac15a279a4ec4f2bb042a14178fff4854f09a091d109e2e56d00310caeb47807bacf49007ee95c38cc23a9de7846a7b908231881d86ceee4ca3020dae09b82ca86c68c25fae84af42ecc889e99ced0235fdc1ca307679b6811c07f26c8c41c307970c3499d13e86b0868eccae7ae9f25d4afb11a10d23a6c1970d2a3bb7d527bb8f40d7140985bb0758745e94927aea8c14badd6670dd7bc21201e6e7ca0b08ae847ed436194ca2b657ade269f5e98f038ec4d1a70667d964f20b0945ab0d0b69edfa8238299600d3dd2c67bf8c9ec6f372bd2dfad4a9538d0d0229d1a2126b2dcc1c8c3af3753c2b5840531963161cc731445c7042351662a60af06a907dc6d4b532ad2e07c8d0971ff9ba0f23fcf1dacac6c74eb09e6cbe9c02c16890501eaf15c0a5e00f02b193ccb8b7565ffabc1971f2bc49a87ea594ed0cac662acffb766411612127117e91606aa20d25725ef567771eda7e125a593f044402af694bc1a051c45364f850461cb2063b0c3f02de12f1183c6b233f77bd041a687b569a33ffb20a4b8f529150732275cdefa1a816d13352768655896f8704883fd6610fa16cb41635262bbd4403891b8d59fdf244b7a56c496ce0ea054b09041114c5bd6797f4b064a1f43fc88012f8077f398773c116b3c78c71d451f80bc033cc63ffba69c2827d0e98ab2fa3c62b506074215c504052446a72d1c3ab09e6b27ceb133eb455ace8a7b67be9dc74103f7e998c6027116d3bfc59f1378302fbec571554d21b87f13b740cc3270b70716eafc178c90a06bdc237d10f3c7b04f447d52b0e7eddd5136b1e36dfe8bf8d8b58415c1f5c47fc50f8f9a1f2281501475084a16d951290f9867130b4feef9860e11048cb77ba467721b060d1ad410eca2cd19fef96d69c13e7469901245820649aae815ea11c871f8b3675ca6f0b0cffcbce5d174f721281d8b641fa722b6ed5851fd4bbc5ed9759b2bb50f752200cc17b27b1d8e17ee591665cb5cb2ce57864c544c02184f527d656d89cdfad8400ab4350d215528066dc22f1a9a738de7000dbb5031459f606ccf2d026c5ad1002a20e1635b9c977c825ea573d3a200116f6359c353b7c8782845d80448a1035024e6ea35ceedea77a532247d5547c8c6ca13fb5ac67841bba0b3f6de23e78a000d1a27ba9ee251cae93be4462e133b4bf09a2a115361cc79a28e8777253bf420e114b50bdd688dff462b913c972908afff7308f568f8abca43b11a9968fa79b079532f6021d0900156a13e78581ea474637ca906417382c3cff7ce521b6293a0e8df6ff16b0c7f859bc83cc1fafa1ef70e0ad8a4827b5ad8eae680bf409f8d505487d7780e445d017f87eb9f444b97244309f0f3df8781a926633b59595befd00156a51da3f9929251cba46f0048a147118397356573e0ec3d448695442cfa10fc550f16372031273ae04a3c2a2867d055ccc7087bd7a1e874bcaea537af16c0733d83e6d854ab7fcd4eb9ecf8ddf5e73039273cd0241f975a635f8a7ffcd29011ca50c6b0e67121074cd4b528b6318be07f491516aca4c37a8c71640d0d0fc0a2da16761c625788f73318255e4ec17672140543143370b6372d4516d2dacea04f1c591fae7683202d9e61767cf06d4150ad9a5a683d4231c85c5ff8982db3907356c26114a6b9017d9735f472c3c78aee7e144b4e30a79fa02dc10d9c2457b0c17cc89b3baaaa3d1f71dc88605c88ca25e44961a03593e320e23656da53bc80037850903931e8fcf30c9c2b3e3e890bde4df451addb34075f8d1d504cfca660049cd3b26e1aafc9b71d81fb04fea639b5a9b4356c41ddb54fb4643224a00ca03aee916d0f8464b309bd84e632452cd651f49ed879bf1ff28badca676f1c9bc07ad4f2e8583e3dc56f45880455725576cbbb252ba5d0a03253276e6ff4582cd03cd88545bffad9f91e0cad0ee710296d4a6fb08d67c23b6b0be9773d6a007dd03a27eb2473cb49ca915b6b0667e469a1349f7177c82f6998e31ca50fffad806065d5d9ffd2e7ed4d6d9d20ddf656444539db5f363b54268c9bf432bddf1aa130412e8650021ad8ec641ae2434e602cfe497ff05eb7fbfe4a36c2b6b041b010000f7919299fc2126e1c079d7fd422358720a9da684650d3e4c13e81c753e3292038f4334016682dafbb2d9de60a0f51e2452493413b4c26cb93f08877fb8bbf70cca6f28243f97f2b952f2991ecda6b72efbdf2c6a38c2e65c5d116dcf10e4ba0dd60258d8bbe58ae9d03fd29d7e7f8f7a956c14047dba2cada3532cae9de8f50556642d74bd35e5349cb2427c55265eb9ed747f7f716b827ce710dbe89b01270b92ed5fe61b7302374814889918a2c5a8f1cfb578a3b8d84cf46bc475e692bc029fba2f3077974569f838a010e3436789e50495f7d402222daaf79c6ec2f81d0e2db6e614e04cf45418b7d7b1c598aba9690ed6af060715979e9a7798af7c30037e365f43ebd7718d5ed45f60e566066fe99c1f388726ba6cb7421e087612eb07", 
        "Ci": "0c9d214aeba9ec129a5630f66b41c753f5c15872444273c45122765d94ba80d9fd9c73050e9d3c262135bb84ef5a15d03143d1ca09def9ac9eea874ff7db01aae8f739f224afd022db8ee2ab236fecaf5ee353824b17e3502b3e6ed43f41ec9229c1033000dbc1a00351b7bc7f895f9d002b5003d54c2503f0f4f2e1db53877d3e957b5bdd6d7949b5b3fc0ce2ba3bac067c1a7dc9e15d928be5f800fea1cd03cd6dbb9450de2cc15b7c5159843b15a543ec095426a06c095c13d8f54a0c19ff994f7c911a6cffd3d3a487f9c6263a639ed306ead250999a3ea05db8064ec0ed775ed4ff6b52e5548b5b03f02e15c89b93145a3fb54452ed64a492f9ff9021ad92f0be7616b5058fca5db1b144616f8575f67cae754e6fc8a6978fc6eaeceb772915dd0fb01898bd5887a822aac1fdbcbd49b47a5dc32c778d77584c75bee7f50def8094bad500d5b1d2155cfb92650dbd460d2ef579701735943068a91677f1ef3ec3c0f24f1b007ee0ca50c586a30b8a0b3ae18c4a7b08d85e2e9b3fa08c3d5374c019fe7ccb51a0c7b1dbf0bb1104ce796e087b943c23c603fd60321cf58319e92e292a48bf721554cdc7e58980c122b6ee568827678c35a9b3748f01eca1fefcb9fa45e9f52f6f0d16113e9d18c978fa63e824d9e8e65152c2e07386d5d13afd49f898b34e0ffc1593157e004d7077260ebcdff8014b170054f18c16637f339d446bf844c15f09a742db537670451c3ed3e81d1797e53f2e4f95827f4b4c6a645cfc1826a869f92ffbd33dd789eb5789c1e98a44521c2665d04b64ded9bb7731925002fd9206b69927cd14e80df66c792d4cf5da85943c2cebb34c93ac643653eb46a8dcd106d35e2860d2f29fed0731a467c70897d303e67228fddb8bb5441aa066897db1f4ec4ba65657f767d64db0374bce26ee46f45c963d8e3818dc0568d369e8dd231f2efde8ec2989c71c9c72a00dfda5b40e1e83c3f632f773ccf338f12d26180a6ccc8ea8d21c1689253dee26f434a929d9cf289e7e229fe357601186a198adc4e9fd5f3ccc9219acc9a9166e4ee8cc2193f79ba1d35a2cc56974f8c89e2e66f2e4f8b90a13f1ac7ab07d2e1cbc329f4265cbe5c5d0f117f669a32081f8489f2576ce0a73debd7771c9e4c08c40d1afa30861fae64c61203a59d15a3fe2d9ad30fd3befd1e4616bdfdb16da30098205a7580ed996824ac44ec74fdf4cd318e386726d9b59a7597e532edf8531a0c55ccabb380dfc4d9d1e3989584469bd9c5eb52963051cd587bcd05e639e08f6e413c29b9375e557ea4134a2edd9f04e80fbd6d605eb9541dc6e1f9b93eaa86c618e8ff5434f56edff74fe74e7927febbfd631f5bd2785f63c1b830ca2d140d631f219d9c1803518bab0600b6d43a4d607a46caa38bfaa955e41917d67f985dff1565547af87938cc05595ed4490254b40dd55623e4f63399c97f7f3f12c4689ec1a2cdfba2c10a7902796e58f510b6368ab49f5da7f70940896ba90ccbf919b2d7688738cc8fa846f97a1a0b31003d05374f5a357347d3cda64d0bb6a9708ca45e263041dd9d1e145df6bd16f9232e6e8900920fd33da2d60f91e1ef249f19bac0c6b929422434a18253ceb0e1e2b06c399ef277ff719922c41e75f07b57fde5a8ac246548f7c4cea0571a85a40064893380e4ab1aa143bff9961bd23a82097a26a9b20676175a9c3918306e7369ec24a11616717336a8c1ddb27f904f1d9319ca784ad4b64b743d0385c92fc502e3662d96d2559668d843919ef610e7e0d78258fe2da03830ef4aa127ea66687eab08927b301bad63e8d102aec6d3c099916bb5a4365a760e473549e839ef7875e7bf23bb14c51b599e2f4e1e528dea463000efc10b300b9273baa5649a2a99dd291abe0b12b0afa377fe120bb161c6df838057bcd02440f655ecfdfb2453599a04e3d434f326c81bd806d0a0a1f38a26b10cb191c24c2beef5941ca52b14e5c46eb377e0c0ded531e5f9483705ed938dd4e0ede3dd2ded5c355161dbf25d1d43780c891a8aceb70ded41b03eefa9856e0d9fa67eae27d18c1965c436b01b0c621ce6dab100b1ca33fc64cd8e2c67a01107aa28cff3cc73ff11ab86808532c1fca823bdf0298b677f4097d19f3a302672c48c8ad0fb9782d66841fbe3c65d7c9a9b1aa8ab0f79f5d0170353e5f7cb2f2f60ac41cde63ad459f78aa26f45bf23f4af392b31d4f2fdc29058ecaa7afb2e587510bba11c88138e4533d9be46e55369ae56851e35444a65506805fa7fd264b8788446527a6bc48627a7a2490bb0ffa2315321f8fc0f35fdff6f8da13ee44afbee2c8815d4b68a83d732d02d548fd20dd5f8370a5533efc2a3b3d21b5c59a6e74195eab563a917fd24fe089d2e72aed7f11120e4eee10a7ebe028c6b9b07e85da137f7c7b8a72ebe1eee0cdfdc824366bf649acd793c6403180b3d4f3a1a4902f7b02da94266b103c6e70e32935bfc1cd09e28333fe5af55835470ca22dca3652133646bb25f1d183c95562dcb50a6d4999502799191348a078690ac8f396966f94754ea7b16b929fcd76ad05f49689a31ab5f01d279f87600148e3e0fc41d30e72085c1351a1207e24ce4d84ec4f6187250f92d64bae6a5e59d752ffade11344ecc2ad644883e9e72f1d572ae7f6194699e69b5318d3422e8b445e70cfe13f87c9b6a30d8d8d928dc14fe007ab54eff1170c60ee6bf24c072fbdc0f9ec8ed74e12f8e58775b77ba7e643671747106283a3f6ea8fddd99786a5b625abbbf3007e3c95496c40555c664781af7d14df055aec70ccef03bd7709a0aa71bcd91099a5f884b77a482c754a65458c41c31385fdeb2c4a008588ec861bb4ab7db91fd717c87074a30172b80086b27bf8d6"
      }], 
    "MGs": [ {
        "ss": [ [ "53dafabfb8b5e68bf58db9adbe2755f9b83d03b34ecf9148dc21b5f2770ab30a", "7b7206464a7abdfd535317870c4c8b2e229f71d2ea8ab65c6e40ad1e38e22703"], [ "317334798bbfc3457dcc2ba95149dc8b53c547dcbe731d1c0d1c1b7e440c9b0c", "edcc60ef703e180819a1723eba431b7337fa83a4fc045b0cc2012e466198d50e"], [ "b541cadaa92a81e2866e9b698fc5c9dea04b0acbea77d22cf5c21e53bc5a8f00", "ae3ab7e9c4b07c627043bb700b8f31fd7a4da34cc535376f251d0139fc8a7e0d"]], 
        "cc": "f70d0d00da28c283564b045961c7f571272c12ec1d307a4f0b4adfe9b496ce04", 
      }{
        "ss": [ [ "a7a951ac56a18a78a37e04f4e34a7e790505f9694c9c6ef8bbdb1e066c4d1008", "67c6fd21c94e9bbc866bee14ceb44a31391062a7bb400cac09996e6c48c6f106"], [ "fccb78a6efdaad806050eba47571907607d4287bf32a07f819b6a9907befac03", "d408817790b3f18019ac2b7fe8ca0925e1cf16a9bf8dd1ece6a9014f6a8be50d"], [ "7dddcf6c069c310bf0d556248a238bff3f349a41d54b9ec84ca7ae2ce8e7a201", "a78985edc0d4d943dc5eeeea988cf95e117c9a12733ebfe8908760aedfe1710f"]], 
        "cc": "0f9640f4a119d13ecec396c85b39134aafd2c06db52c00ee9514b6ae6730d20e"
      }]
  }
}
