### ISSUE TITLE
readline prompt displayed after each output line in incoming_transfers

### ISSUE THREAD

**Issue by moneromooo-monero** [monero-project/monero#2104]
eg:

               amount   spent    unlocked  ringct    global index                                                               tx id
      10000.000000000       T    unlocked       -          473514  <f58314d3f9a137c94f550df79c752570f382bfca9132b17eb90f75907fc4a733>[wallet 9zcJy2]

Probably other commands too. I've just tried show_transfers, and it shows up too.

**Comment by jtgrassie** [comment]
I will check. Most likely reason is missing EOL on the output, hense prompt redisplay truncating output.

**Comment by jtgrassie** [comment]
Actually it could also be something else as well. Multiple line log output needs looking at here.

**Comment by jtgrassie** [comment]
I'm not actually getting any output from `show_transactions` whether with or without readline support. Any idea why that could be?

**Comment by moneromooo-monero** [comment]
From show_transfers, you mean ? If so, it could be that all your txes on that wallet were made before the data for show_transfers was kept. If not, it appears to be a bug.

Also, when you refresh a wallet and it takes a while, you see just the end of the counting messages, the first part is hidden by the prompt. This is possibly the same bug, so I'm not opening one for now.

**Comment by moneromooo-monero** [comment]
You could try the get_transfers RPC to see if you get any data. That'll tell you whether it's missing data or output bug.

**Comment by jtgrassie** [comment]
@moneromooo-monero I'm not sure why it was doing that but I rescanned and that fixed it. I'm working on the readline prompt issues at the moment. I just need to find all the commands that cause the issue!

**Comment by jtgrassie** [comment]
Fixed by #2112

**Comment by moneromooo-monero** [comment]
Also the "tx saved as..." line when creating a tx from view wallet (probably also fixed by your patch, I'm just mentioning it here so I remember to check when I test your patch)

**Comment by moneromooo-monero** [comment]
Using 2112, I still see things like a command being hidden, eg: at the prompt, I type a command, then enter. This erases the command, and just displays the prompt. Due to the temporary hang filed elsewhere, this looks like it's completely been ignored. Later on, a password prompt comes up on the same line, and you see: [wallet A27QfV]: Wallet password: 
So it needs to echo the user's newline.

**Comment by moneromooo-monero** [comment]
There's another manifestation of that bug, which hides random messages. For example:

sign_transfer xxxxx

xxxxx being an existing file, but a multisig unsigned tx. The signing fails (since the file isn't the expected cold wallet information), but that message does not show up (though it does appear in the log, as expected). It's hidden by the prompt.

**Comment by moneromooo-monero** [comment]
I'm using all the patches, including the process lock and my patches to fix the random delay in readline stop.

**Comment by moneromooo-monero** [comment]
All this seems fine with latest patches.
