### ISSUE TITLE
Monero GUI Windows 10 64bit - crashed during wallet sync

### ISSUE THREAD

**Issue by TrojanZA** [monero-project/monero#2532]
Hi

Not sure if this is the right place to log this, please redirect if I should be going elsewhere.

I ran monero-wallet-gui this morning. All going well, wallet opened and was doing the refresh, where it started hanging at around 30k blocks left. Have opened the CLI and sync completed without a hitch.

**Comment by moneromooo-monero** [comment]
Can you get a stack trace of the crash ?
If the wallet hanged and something crashed, it's monerod that crashed. I can't give instructions for windows though, so if you don't know how, ignore it. If it was a moneord crash, it's most likely fixed on master though.

**Comment by moneromooo-monero** [comment]
Please test with new master, where 2492 is merged, and a likely fix for your crash.

**Comment by moneromooo-monero** [comment]
2492 is now merged, so testing current master will use the patch.

**Comment by moneromooo-monero** [comment]
No more info, and the crash is likely 2492, closing.

+resolved

**Comment by BernhardSchlegel** [comment]
I can confirm, that the issue still exists, I'm on `monero-gui-v0.11.1.0`. Last logentry in "monero-wallet-gui.log" is `2018-03-13 08:16:53.915	13872	WARN 	wallet.wallet2	src/wallet/wallet2.cpp:2505	Loaded wallet keys file, with public address: XXX`. How can I provide further details ? Windows 10 Pro, Version 1709, Build 16299.248. 

Thanks & Cheers
