### ISSUE TITLE
get_tx_key not supported by HW wallet?

### ISSUE THREAD

**Issue by eigenbrot** [monero-project/monero#4858]
I'm using a Ledger Nano S as a HW wallet and have `store-tx-info = 1` in monero-wallet-cli version v0.13.0.4. If I try `get_tx_key` the result is **`Error: command not supported by HW wallet`**.

Is this the correct behavior? [This](https://www.reddit.com/r/Monero/comments/8xhijh/using_ledger_comes_at_the_expense_of_functionality/) post suggests that this functionality has not been added yet. If this is true is there any way at all to recover a tx key? (I'm guessing no)

Thanks!

**Comment by moneromooo-monero** [comment]
AFAIK, the secret tx key is kept on the device, and the monero wallet does not know it. I think the wallet software gets an encrypted version, so it seems possible that code could be added to get the ledger to decrypt it if necessary.

That's my understanding, which may not be correct since I didn't write that code.

**Comment by moneromooo-monero** [comment]
Ledger will support this in the near future.

**Comment by ph4r05** [comment]
Trezor supports this feature, now in master due to #5211

**Comment by golya87** [comment]
> Ledger will support this in the near future.

Do you know any ETA for this?

**Comment by dEBRUYNE-1** [comment]
@golya87 - Should be included in the upcoming v0.14.1 release.

**Comment by golya87** [comment]
Sounds promising.
Where can I find a roadmap or relase date for this version?

**Comment by dEBRUYNE-1** [comment]
Quoting myself:

>I can only provide soon as ETA. Yesterday, almost all remaining pull requests (for the release) have been merged though. Thus, I think we are close.

**Comment by dEBRUYNE-1** [comment]
CLI v0.14.1.0 has been released. GUI v0.14.1.0 will be out soon.

**Comment by dEBRUYNE-1** [comment]
+resolved

**Comment by ph4r05** [comment]
Just a note: this PR requires following PRs to be merged to monero-core (and monero-gui to use the updated monero-core)

- https://github.com/monero-project/monero/pull/5662
- https://github.com/monero-project/monero/pull/5673

**Comment by Paycho** [comment]
This issue appears to still exist for Ledger Nano S's - as I unfortunately found out today, while needing to prove a transaction. Highly recommend not using a Ledger until this is fixed.
