### ISSUE TITLE
Multisig tx signing aborts with "Transaction prefix does not match data"

### ISSUE THREAD

**Issue by rbrunner7** [monero-project/monero#5130]
Signing of multisig transactions (current master HEAD) aborts in `wallet2::sign_multisig_tx` with an error message of "Transaction prefix does not match data", currently output at line 6412.

Reproduce as follows:

* Configure multisig wallets. 2/2 multisig suffices
* Fund the wallet, sync, wait for unlock
* Start a tx in one wallet
* Try to sign it in the other wallet using the CLI wallet command `sign_multisig` -> Error

I and some other fellow MMS tester tried 2/2, 2/3 and 3/3 multisig, on Stagenet and on Testnet: It seems it's always the *second* signature that fails (the first of course happening together with the `transfer` command).

With a litte trial-and-error I found out that with the code at [this commit from January 18](https://github.com/monero-project/monero/commit/b7441c4a328f32cdf33f8e07816bcb080483d4cb) signing still works, but with one more commit included, the [pruning commit from January 22](https://github.com/monero-project/monero/commit/b750fb27b0f20e9443827732b69a504a76036430), it does not work anymore.

Wallet construction seems to be ok: Even with the wallet constructed with latest HEAD code signing works with the pruning PR left out, and stops to work with that included.

**Comment by tmoravec** [comment]
Can reproduce with 2/2 wallets.

**Comment by tmoravec** [comment]
Logs from the CLI wallet: https://paste.debian.net/1066985/

**Comment by tmoravec** [comment]
The tx hash of the transaction obtained from `cryptonote::construct_tx_with_tx_key` is different from what's in `exported_txs`.

**Comment by naughtyfox** [comment]
We faced this issue as well. The problem was in dummy encrypted payment id and was already fixed.

**Comment by moneromooo-monero** [comment]
So it's fixed ?

**Comment by rbrunner7** [comment]
I just tried with latest HEAD: Still does not work for me.

@naughtyfox 's statement also somehow contradicts my own earlier result that it works with the pruning PR left out, but does not work with that PR included. Anyway, as I said, current HEAD (unmodified, with all PRs in) still gives me that `Transaction prefix does not match data` error.

**Comment by rbrunner7** [comment]
Ah, maybe, @naughtyfox sees a connection between this issue and the issue solved in
PR #5270. Well, wouldn't that be strange, as that PR is about Wallet API?

**Comment by moneromooo-monero** [comment]
OK, I'll test/fix this soonish then.

**Comment by naughtyfox** [comment]
The problem I solved in referenced PR is not about mismatched transaction prefix. This one happens when you use wallet api for non-N/N multisig transactions.

The quickest way to check if it's transaction extra / encrypted payment id problem is to make multisig tx with non-default payment id. If transaction goes well than the problem still persists.

**Comment by moneromooo-monero** [comment]
After all this debugging, I found the bug. And then I realized... I'd seen that change somewhere.

https://github.com/monero-project/monero/pull/5168/files

**Comment by rbrunner7** [comment]
So ... cherry-pick that to make multisig work again if I want to test, or is there more to it?

**Comment by moneromooo-monero** [comment]
Just that.

**Comment by rbrunner7** [comment]
Verified: Works.

**Comment by moneromooo-monero** [comment]
+resolved
