### ISSUE TITLE
v0.18.4.0 FTBFS: Arch Linux

### ISSUE THREAD

**Issue by Dormouse665** [monero-project/monero#9932]
CMake 4.x.x doesn't like your project:

```
$ git clone <clone_url>
$ cd monero/build
$ git checkout v0.18.4.0
$ cmake ..
CMake Warning (dev) at CMakeLists.txt:40 (include):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /usr/bin/python (found version "3.13.3")
CMake Deprecation Warning at CMakeLists.txt:46 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


-- CMake version 4.0.2-dirty
-- The C compiler identification is GNU 15.1.1
-- The CXX compiler identification is GNU 15.1.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at /home/dormouse/gits/monero/build/CMakeFiles/CMakeTmp/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


-- Found usable ccache: /usr/bin/ccache
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Looking for -Wl,--no-undefined linker flag
-- Looking for -Wl,--no-undefined linker flag - found
-- Looking for -Wl,-undefined,error linker flag
-- Looking for -Wl,-undefined,error linker flag - found
CMake Error at /home/dormouse/gits/monero/build/CMakeFiles/CMakeTmp/test_project/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 has been removed from CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.

  Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.


CMake Error at CMakeLists.txt:235 (try_compile):
  Failed to configure test project build system.
Call Stack (most recent call first):
  CMakeLists.txt:248 (forbid_undefined_symbols)


-- Configuring incomplete, errors occurred!
```

**Comment by SyntheticBird45** [comment]
Weird, Arch CI build it successfully tho: https://github.com/monero-project/monero/actions/runs/15240535234/job/42860042197?pr=9936

**Comment by nahuhh** [comment]
https://github.com/monero-project/monero/commit/0d0a656618e396de7ff60368dde708ad9d45f866

fixed on release branch already

**Comment by Dormouse665** [comment]
This fixes my error, but it doesn't fix the deprecation warning.

Should I make a PR with requirement bumped to 3.10?

**Comment by selsta** [comment]
I'm not sure it's worth upgrading the min required version just to fix a warning.

**Comment by Dormouse665** [comment]
The warning is going to become an error one day and then I will be back reporting this again.

**Comment by Dormouse665** [comment]
I tried fixing this in CMakeLists.txt in the root.
It makes the build run, but there are still warnings present.

I edited both minimum versions, one for the file itself, one that is used
to generate some other.

I have tried 3.10 (modification of your current version to minimum required for
cmake to shuddup) and 3.31.0 (Which is probably the version present on Arch last time
I have decided to bump the version in my AI project.)

I am not able to solve this one on what limited time I currently have for open source development:
```
CMake Deprecation Warning at /home/dormouse/gits/monero/build/CMakeFiles/CMakeTmp/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.
```

I am also ignoring ones from external projects, about which I encourage
you to reach out to developers of.

If any dev is willing to walk me through how you handle CMake stuff,
I could help maintaining it so that Monero can avoid such build
fails in the future.

**Comment by selsta** [comment]
I'm closing this as the original issue itself was solved, the only issue remaining is the warning. I will consider updating min CMake to 3.10, as Ubuntu 18.04 is the lowest we support currently and it ships with 3.10.
